/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CreateStudentForm: typeof import('./src/components/CreateStudentForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StudentsTable: typeof import('./src/components/StudentsTable.vue')['default']
    UpdateStudentForm: typeof import('./src/components/UpdateStudentForm.vue')['default']
  }
}
